# ---------- build ----------
FROM golang:1.26-alpine AS build

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o watcher-agent ./src/main

# ---------- runtime ----------
FROM alpine:latest

WORKDIR /app

RUN apk add --no-cache ca-certificates

COPY --from=build /app/watcher-agent /app/watcher-agent

EXPOSE 8080

ENTRYPOINT ["/app/watcher-agent"]
