# ---------- build ----------
ARG GO_VERSION="1.26.1"
FROM golang:${GO_VERSION}-alpine AS build

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

ARG TARGETOS="linux"
ARG TARGETARCH="amd64"

COPY . .
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -o watcher-agent ./src/main

# ---------- runtime ----------
FROM alpine:latest

WORKDIR /app

RUN apk add --no-cache ca-certificates

COPY --from=build /app/watcher-agent /app/watcher-agent

ENTRYPOINT ["/app/watcher-agent"]
