FROM golang:1.26.1-alpine

RUN apk add --no-cache \
    git \
    curl \
    bash

RUN curl -sSfL https://golangci-lint.run/install.sh \
    | sh -s -- -b /usr/local/bin v2.11.4

WORKDIR /app

#CMD ["go", "mod", "tidy"]
#CMD ["golangci-lint", "run"]
CMD ["go", "run", "./src/main"]
