ARG GO_VERSION="1.26.1"
FROM golang:${GO_VERSION}-alpine

WORKDIR /app

RUN apk add --no-cache \
    git \
    curl \
    bash

RUN curl -sSfL https://golangci-lint.run/install.sh \
    | sh -s -- -b /usr/local/bin v2.11.4

#CMD ["go", "mod", "tidy"]
#CMD ["golangci-lint", "run"]
CMD ["go", "run", "./src/main"]
